session_name: ete-sync
start_directory: ~/Work/ete-sync-heroku-docker/

windows:
  - window_name: git
    start_directory: ~/Work/ete-sync-heroku-docker/projects/ete-sync-heroku/
    panes:
      - shell_command:
          - lazygit

  - window_name: sync
    start_directory: ~/Work/ete-sync-heroku-docker/projects/
    panes:
      - shell_command:
          - nix develop ./nix
          - cd ./ete-sync-heroku
          - source .venv/bin/activate
          - setsid -f pycharm . > /dev/null 2>&1 < /dev/null
          - python manage.py runserver 0.0.0.0:8000

  - window_name: catalog
    start_directory: ~/Work/ete-sync-heroku-docker/projects/
    panes:
      - shell_command:
          - nix develop ./nix
          - cd ./ete-sync-heroku
          - source .venv/bin/activate
          - python manage.py runserver --settings=catalogapi.settings 0.0.0.0:7011
