session_name: buyete-ui
start_directory: ~/Work/ete-sync-heroku-docker/

windows:
  - window_name: buyete
    start_directory: ~/Work/ete-sync-heroku-docker/projects/buyete-sync-ui
    panes:
      - shell_command:
          - setsid -f webstorm . > /dev/null 2>&1 < /dev/null
          - yarn run dev

  - window_name: git
    start_directory: ~/Work/ete-sync-heroku-docker/projects/buyete-sync-ui
    panes:
      - shell_command:
          - lazygit
