session_name: buyete-ui
start_directory: ~/Work/ete-sync-heroku-docker/

windows:
  - window_name: buyete
    options:
      automatic-rename: off
      allow-rename: off
    start_directory: ~/Work/ete-sync-heroku-docker/projects/
    panes:
      - shell_command:
          - cd ./buyete-sync-ui
          - setsid -f webstorm . > /dev/null 2>&1 < /dev/null
          - lazygit
